apiVersion: v1 
kind: ConfigMap
metadata:
  name: myconfig
  namespace: myapp
data: 
  test.conf: |
    digitalOceanToken = {{ .Values.digitalOceanToken  }}
    enableAwesome = "true"
    version = "v2"