replicaCount: 1

image:
  repository: nanajanashia/argocd-app
  tag: "$TAG"

service:
  name: myapp-service
  port: 8080
  targetPort: 8080
  protocol: TCP

externalVariables:
  digitalOceanToken: "prova123562"
